{{ if eq .Values.distribution "kubernetes" }}
kind: Ingress
apiVersion: networking.k8s.io/v1
metadata:
  name: {{ .Values.name | quote }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  tls:
  - hosts:
    - {{ .Values.application_domain | quote }}
    secretName: ingress-tls
  rules:
  - host: {{ .Values.application_domain | quote }}
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: {{ .Values.name | quote }}
            port:
              number: 8080
{{- end }}
